### ISSUE TITLE
pcall error

### ISSUE THREAD

**Issue by RandomOtter** [Mathijs-Bakker/dotfiles#8]
Hey Mathijs

i keep getting a pcall error when i run nvim i am on archlinux couldn't find anything related to it on the net or i am just unlucky in finding it 

this is the error i am getting 

https://i.imgur.com/16rehGV.png

lua server is setup like it should 

Thank you and your nvim config  is really good with unity kudos for making it public

**Comment by RandomOtter** [comment]
fixed now 

changed Plugins.harpoon >> plugins.harpoon and removed the git plugs

**Comment by Mathijs-Bakker** [comment]
``pcall`` is a Lua function. It's like a ``try-catch`` in csharp.
I am using it in a global wrapper function TrySource. When it fails to source `(require('..'))` a file it throws an error with a stack trace. While it still loads Neovim.

It's giving you just that little info that you might need.

**Comment by RandomOtter** [comment]
that helped me alot thank you
